version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_wisata
      POSTGRES_PASSWORD: empirise
      POSTGRES_DB: db_data_peserta
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
